apiVersion: v1
data:
  pscheduler-agent.json: |
    {
        "match-addresses": ["{{ .Release.Name }}-headless"],
        "remotes": []
    }

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pscheduler-agent-configmap
