{{- if .Values.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    {{- include "perfsonar.labels" . | nindent 4 }}
    {{- if .Values.service.headless.annotations }}
  annotations:
    {{- toYaml .Values.service.headless.annotations | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- include "perfsonar.servicePorts" . | nindent 4 }}
  selector:
    {{- include "perfsonar.selectorLabels" . | nindent 4 }}
{{- end }}
