{{- if and .Values.service.default.enabled (not .Values.multus.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "perfsonar.labels" . | nindent 4 }}
    {{- if .Values.service.default.annotations }}
  annotations:
    {{- toYaml .Values.service.default.annotations | nindent 4}}
    {{- end }}
spec:
  type: {{ .Values.service.default.type }}
  ports:
    {{- include "perfsonar.servicePorts" . | nindent 4 }}

  selector:
    {{- include "perfsonar.selectorLabels" . | nindent 4 }}
{{- end }}
